import 'package:dart_monty/dart_monty.dart';
import 'package:dart_monty/dart_monty_testing.dart';
import 'package:test/test.dart';

/// Generated by: python scripts/generate_monty_schemas.py --model tool
const _validateToolPython = '''
def validate_tool(raw):
    result = {}
    result['kind'] = str(raw.get('kind', ''))
    result['tool_name'] = str(raw.get('tool_name', ''))
    result['tool_description'] = str(raw.get('tool_description', ''))
    result['tool_requires'] = str(raw.get('tool_requires', ''))
    result['allow_mcp'] = bool(raw.get('allow_mcp', False))
    result['agui_feature_names'] = list(raw.get('agui_feature_names', []))
    result['extra_parameters'] = dict(raw.get('extra_parameters', {}))
    return result
''';

const _usage = MontyResourceUsage(
  memoryBytesUsed: 1024,
  timeElapsedMs: 10,
  stackDepthUsed: 5,
);

MontyResult _makeResult(Map<String, MontyValue> entries) => MontyResult(
  value: MontyDict(entries),
  usage: _usage,
);

void main() {
  group('Schema spike: validate_tool via MontyPlatform.run()', () {
    late MockMontyPlatform mock;

    setUp(() {
      mock = MockMontyPlatform();
    });

    test('returns validated dict with correct types', () async {
      mock.runResult = _makeResult({
        'kind': const MontyString('search'),
        'tool_name': const MontyString('tools.search'),
        'tool_description': const MontyString('Search indexed documents'),
        'tool_requires': const MontyString('bare'),
        'allow_mcp': const MontyBool(false),
        'agui_feature_names': const MontyList([MontyString('code_execution')]),
        'extra_parameters': const MontyDict({}),
      });

      const code = '''
raw = __input__
$_validateToolPython
validate_tool(raw)
''';

      final result = await mock.run(code);

      expect(result.error, isNull);

      final value = result.value.dartValue! as Map<String, Object?>;
      expect(value['kind'], 'search');
      expect(value['tool_name'], 'tools.search');
      expect(value['tool_description'], 'Search indexed documents');
      expect(value['tool_requires'], 'bare');
      expect(value['allow_mcp'], false);
      expect(value['agui_feature_names'], ['code_execution']);
      expect(value['extra_parameters'], <String, Object?>{});
    });

    test('code sent to mock contains validate_tool function', () async {
      mock.runResult = _makeResult({
        'kind': const MontyString(''),
        'tool_name': const MontyString(''),
        'tool_description': const MontyString(''),
        'tool_requires': const MontyString(''),
        'allow_mcp': const MontyBool(false),
        'agui_feature_names': const MontyList([]),
        'extra_parameters': const MontyDict({}),
      });

      const code = '''
raw = __input__
$_validateToolPython
validate_tool(raw)
''';

      await mock.run(code);

      expect(mock.history.lastRunCode, contains('def validate_tool(raw):'));
      expect(mock.history.lastRunCode, contains('validate_tool(raw)'));
    });

    test('handles missing fields with defaults', () async {
      mock.runResult = _makeResult({
        'kind': const MontyString(''),
        'tool_name': const MontyString(''),
        'tool_description': const MontyString(''),
        'tool_requires': const MontyString(''),
        'allow_mcp': const MontyBool(false),
        'agui_feature_names': const MontyList([]),
        'extra_parameters': const MontyDict({}),
      });

      const code = '''
raw = __input__
$_validateToolPython
validate_tool(raw)
''';

      final result = await mock.run(code);

      expect(result.error, isNull);

      final value = result.value.dartValue! as Map<String, Object?>;
      expect(value['kind'], '');
      expect(value['allow_mcp'], false);
      expect(value['agui_feature_names'], <Object?>[]);
      expect(value['extra_parameters'], <String, Object?>{});
    });

    test('coerces types from loosely-typed input', () async {
      mock.runResult = _makeResult({
        'kind': const MontyString('42'),
        'tool_name': const MontyString(''),
        'tool_description': const MontyString(''),
        'tool_requires': const MontyString(''),
        'allow_mcp': const MontyBool(true),
        'agui_feature_names': const MontyList(
          [MontyString('a'), MontyString('b')],
        ),
        'extra_parameters': const MontyDict(
          {'key': MontyString('val')},
        ),
      });

      const code = '''
raw = __input__
$_validateToolPython
validate_tool(raw)
''';

      final result = await mock.run(code);

      expect(result.error, isNull);

      final value = result.value.dartValue! as Map<String, Object?>;
      expect(value['kind'], '42');
      expect(value['allow_mcp'], true);
    });
  });
}
