include:
  - package:very_good_analysis/analysis_options.10.0.0.yaml
  - dcm_options.yaml

analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true

linter:
  rules:
    public_member_api_docs: false
